    
# Generated by Django 2.2 on 2019-04-20 03:42

from django.db import migrations
from ..SQL_Create_Table import *
from django.db import connection


def make_trigger(apps,schema_editor):

   with connection.cursor() as cursor:
      cursor.execute(CREATE_ALL)


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]