# Generated by Django 2.1.5 on 2019-04-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE TABLE Pen (
                name VARCHAR (20)
            )"""
        )
    ]
