# Generated by Django 2.2 on 2019-05-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20190419_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
