# Generated by Django 2.1.5 on 2019-04-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20190419_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
