# Generated by Django 2.1.5 on 2019-05-01 05:47

from django.db import migrations
from ..SQL_Create_Table import *
from django.db import connection



def make_trigger(apps,schema_editor):

   with connection.cursor() as cursor:
      cursor.execute(create_table_procedure)



class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_auto_20190429_0506'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
