# Generated by Django 2.1.5 on 2019-04-20 00:13

from django.db import migrations
from ..SQL_Create_Table import *
from django.db import connection

def make_trigger(apps,schema_editor):

   with connection.cursor() as cursor:
      cursor.execute("""
            BEGIN;

            DROP TABLE employee, doctor, receptionist, admin;

            COMMIT;""")






class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_auto_20190417_0258'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
