# Generated by Django 2.0.5 on 2019-04-27 02:18

from django.db import migrations
from ..SQL_Create_Table import *
from django.db import connection

def make_trigger(apps,schema_editor):

   with connection.cursor() as cursor:
      cursor.execute(create_table_procedure)


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_auto_20190420_0024'),
    ]

    operations = [
        migrations.RunPython(make_trigger)
    ]
